version: 1
builder:
  configs:
  - platform: ios
    scheme: SwiftUIGamepad
  - platform: macos-xcodebuild
    scheme: SwiftUIGamepad
  - platform: tvos
    scheme: SwiftUIGamepad
  - platform: watchos
    scheme: SwiftUIGamepad
  - documentation_targets: [SwiftUIGamepad]
